version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoAdmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoAdmin
    networks:
      - myiot-bridge
    ports:
      - 27019:27017
  mosquitto:
    build: ./mosquitto
    container_name: mqtt
    networks:
      - myiot-bridge
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/config
      - /mosquitto/data
      - /mosquitto/log
  
  backend:
    build: .
    container_name: backend
    networks:
      - myiot-bridge
    ports:
      - 8080:8080
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=mongoAdmin
      - MONGODB_PASSWORD=mongoAdmin
      - MONGODB_DATABASE=iotProject
      - USER_MASTER_PASSWORD=Master@123
      - USER_MASTER_MQTTPASSWORD=8ae4bd82-7403-4d7e-b5b3-1f48b5328a50
      - MQTT_URI=tcp://mqtt:1883
      - MQTT_SYSTEM_PASSWORD=System@123
      - MQTT_DYNSEC_USERNAME=dynsec
      - MQTT_DYNSEC_PASSWORD=Dynsec@123
      - JWT_SECRET=PalavraSecretaParaGeracaoDeJWTTOken
    depends_on:
      - mosquitto
      - mongodb

networks:
  myiot-bridge:
    driver: bridge
